# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gbradhopkins.com
email: me@gbradhopkins.com
description: > # this means to ignore newlines until "baseurl:"
  An assortment of tutorials and thoughts on computers, web design, web services and life online.
baseurl: "/gbradhopkins.com" # the subpath of your site, e.g. /blog
url: "http://firebrandmedia.github.io/" # the base hostname & protocol for your site
twitter_username: gbradhopkins
github_username:  firebrandmedia


# Build settings
markdown: kramdown
future: FALSE
